apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart-deployment-cronjob
  namespace: qtrac
spec:
  schedule: "0 11 * * *"  # Run at daily 11:00 am UTC every, which is 4:00 PM PKT every day
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec: 
      template:
        spec:
          containers:
          - name: restart-deployment
            image: bitnami/kubectl:1.25.11
            command:
            - /bin/bash
            - "-c"
            - |
              echo "Job started at: $(date)"
              kubectl rollout restart deployment qtrac-agent-template-service
              echo "Deployment restarted successfully at: $(date)"
          restartPolicy: OnFailure
          serviceAccountName: deployment-restart-sa
          dnsPolicy: ClusterFirst
          securityContext: {}
          terminationGracePeriodSeconds: 30
          schedulerName: default-scheduler

