apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-restart-rolebinding
  namespace: qtrac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-restart-role
subjects:
- kind: ServiceAccount
  name: deployment-restart-sa
  namespace: qtrac
